### ISSUE TITLE
How can we use python 3 with ROS? Can you help me with it?

### ISSUE THREAD

**Issue by wajeehulhassanvii** [zhuzd12/openai_example_projects#1]

**Comment by wajeehulhassanvii** [comment]
I want to use DDPG but DDPG is mostly available for python 3 only and Ros is implemented on Python 2.

**Comment by zhuzd12** [comment]
Firstly you can run the roslaunch file in one window to launch the environment, and run your scripts in another window using a python3 virtualenv.

**Comment by wajeehulhassanvii** [comment]
> Firstly you can run the roslaunch file in one window to launch the environment, and then run your scripts in another window using a python3 virtualenv.

I tried that, in the custom environment it was importing tf library which is not compatible with python 3. Any workaround for that?

**Comment by zhuzd12** [comment]
That's a point I missed and I can not find an elegant way to solve. So far,  it's best to avoid using tf library in the custom environment or just reimplement it.
